version: "3"

tasks:
  install:
    aliases: [workspace]
    desc: Initialize the project
    cmds:
      - task: install:clean
      - task: install:workspace

  install:clean:
    internal: true
    desc: Clean the project
    cmds:
      - rimraf -g **/node_modules **/pnpm-lock.yaml **/dist

  install:workspace:
    desc: Install dependencies
    deps: [install:clean]
    cmds:
      - pnpm install

  build:
    desc: Build the project
    cmds:
      - task: build:clean
      - task: build:ts
      - task: build:typings

  build:clean:
    desc: Clean the project
    cmds:
      - rm -rf dist

  build:ts:
    desc: Build typescript
    cmds:
      - esbuild build src/**/* --root ./src --outdir dist --splitting --packages external --packages external --sourcemap=inline {{.CLI_ARGS}}

  build:typings:
    desc: Build typings
    cmds:
      - esbuild tsc -p tsconfig.types.json {{.CLI_ARGS}}
