version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - task: build:clean
      - task: build:ts

  build:clean:
    internal: true
    desc: Clean the project
    cmds:
      - rm -rf build node_modules

  build:ts:
    desc: Build typescript
    deps: [build:clean]
    cmds:
      - bun build app/index.ts --root=. --outdir=build --target=browser --packages=external --sourcemap=linked
